events {}

http {

    upstream backend_servers {

        server server1:3001;

        server server2:3002;

    }

    server {

        listen 80;

        root /usr/share/nginx/html;

        index index.html;

        # Dashboard
        location = /dashboard {
            return 301 /dashboard/;
        }

        location /dashboard/ {

            alias /usr/share/nginx/html/dashboard/;

            index index.html;

            try_files $uri $uri/ /dashboard/index.html;

        }

        # Load Balancer
        location / {

            proxy_pass http://backend_servers;

            proxy_http_version 1.1;

            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;

            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }

        location /api/server1 {

            proxy_pass http://server1:3001/api;

        }

        location /api/server2 {

            proxy_pass http://server2:3002/api;

        }

        location /health/server1 {

            proxy_pass http://server1:3001/health;

        }

        location /health/server2 {

            proxy_pass http://server2:3002/health;

        }

    }

}